### ISSUE TITLE
Probleme bei der Veröffentlichung

### ISSUE THREAD

**Issue by jana-lisa** [rstatszh-k009/ogd-daten-jana-lisa#2]
@larnsce ich habe alle Schritte nach Anleitung befolgt, leider ist trotzdem etwas schief gegangen und die Webseite ist nicht zugänglich. Könnte es daran liegen, dass ich anstelle einer Quarto Datei die Markdownvorlage des Kantons verwendet habe?

**Comment by larnsce** [comment]
Liebe @jana-lisa, vielen Dank für das Erstellen des Berichtes. Ich freue mich darauf diesen anzuschauen.

Du kannst gerne die Markdownvorlage des Kantons verwenden, allerdings müsstest du die Ordnerstruktur beibehalten:

1. Ordner `Vergleich der Standortattraktivität` umbenennen zu `docs`
2. Datei `Vergleich der Standortattraktivität.Rmd` umbenennen zu `index.Rmd`

If you have set your Settings for GitHub Pages to publish from the `docs` folder, then this should end up working. Let me know if not and I will have another look at it.

**Comment by jana-lisa** [comment]
Danke @larnsce, habe ich gerade gemacht und committed und gepushed aber das scheint nicht zu klappen! In meinem Repository ist immer noch die Version von vor 2 Tagen :(

**Comment by jana-lisa** [comment]
nach einigem Ausprobieren hats doch noch geklappt :)
